# Node collection
node:
  cassandra:
    config-path: "/etc/cassandra"
    log-path: "/var/log/cassandra"
    home-path: "/var/lib/cassandra"
  collecting:
    configs:
      - "cassandra.yaml"
      - "cassandra-env.sh"
      - "jvm.options"
      - "logback.xml"
    logs:
      - "system.log"

# Metrics collecting
metrics:
  prometheus:
    port: 9090
    data-path: "/data/snapshots/"