# Logs collection
logs:
  cassandra:
    config-path: "/etc/cassandra"
    log-path: "/var/log/cassandra"
    home-path: "/var/lib/cassandra"

# Stats collecting
stats:
  prometheus:
    port: 9090
    data-path: "/data/snapshots/"