# Common settings
agent:
  collected-data-path: "~/.instaclustr/supportcenter/DATA"

# Collecting settings
node:
  cassandra:
    config-path: "/etc/cassandra"
    log-path: "/var/log/cassandra"
    gc-path: "/var/log/cassandra"
    data-path:
      - "/var/lib/cassandra/data"
  collecting:
    configs:
      - "cassandra.yaml"
      - "cassandra-env.sh"
      - "jvm.options"
      - "logback.xml"
    logs:
      - "system.log"
    gc-log-patterns:
      - "gc*"
metrics:
  prometheus:
    port: 9090
    data-path: "/data/snapshots/"

# Collecting targets (node and metric hostnames)
target:
  nodes:
  metrics: