version: '3'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - '9090:9090'
    volumes:
      - ./configs/prometheus:/etc/prometheus
      - ./data/metrics/snapshot:/snapshot
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/snapshot'
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - '3000:3000'
    env_file:
      - 'env.grafana'
    user: "0"
    restart: always
    links:
      - prometheus
    volumes:
      - ./configs/grafana/provisioning:/etc/grafana/provisioning/