apiVersion: 1

deleteDatasources:
  - name: Metrics
  - name: Logs

datasources:
  - name: Metrics
    type: prometheus
    access: proxy
    url: 'http://prometheus:9090'

  - name: Logs
    type: elasticsearch
    access: proxy
    url: 'http://elasticsearch:9200'
    database: 'filebeat-*'
    jsonData:
      timeField: "@timestamp"
      esVersion: 70
      logMessageField: cnode.message
      logLevelField: cnode.loglevel
